/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as LogoutRouteImport } from './routes/logout'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CallbackRouteImport } from './routes/callback'
import { Route as WorkspaceRouteImport } from './routes/_workspace'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkspaceWorkflowsRouteImport } from './routes/_workspace.workflows'
import { Route as WorkspaceStatesRouteImport } from './routes/_workspace.states'
import { Route as WorkspaceSourcesRouteImport } from './routes/_workspace.sources'
import { Route as WorkspaceSettingsRouteImport } from './routes/_workspace.settings'
import { Route as WorkspaceRunsRouteImport } from './routes/_workspace.runs'
import { Route as WorkspaceReportsRouteImport } from './routes/_workspace.reports'
import { Route as WorkspaceOnboardingRouteImport } from './routes/_workspace.onboarding'
import { Route as WorkspaceNotificationsRouteImport } from './routes/_workspace.notifications'
import { Route as WorkspaceLegalRouteImport } from './routes/_workspace.legal'
import { Route as WorkspaceKanbanRouteImport } from './routes/_workspace.kanban'
import { Route as WorkspaceIntegrationsRouteImport } from './routes/_workspace.integrations'
import { Route as WorkspaceInboxRouteImport } from './routes/_workspace.inbox'
import { Route as WorkspaceHealthRouteImport } from './routes/_workspace.health'
import { Route as WorkspaceFormsRouteImport } from './routes/_workspace.forms'
import { Route as WorkspaceDocumentsRouteImport } from './routes/_workspace.documents'
import { Route as WorkspaceDataMapRouteImport } from './routes/_workspace.data-map'
import { Route as WorkspaceDataLifecycleRouteImport } from './routes/_workspace.data-lifecycle'
import { Route as WorkspaceContactsRouteImport } from './routes/_workspace.contacts'
import { Route as WorkspaceConnectionsRouteImport } from './routes/_workspace.connections'
import { Route as WorkspaceClientsRouteImport } from './routes/_workspace.clients'
import { Route as WorkspaceCapabilitiesRouteImport } from './routes/_workspace.capabilities'
import { Route as WorkspaceBrainRouteImport } from './routes/_workspace.brain'
import { Route as WorkspaceBillingRouteImport } from './routes/_workspace.billing'
import { Route as WorkspaceApiRouteImport } from './routes/_workspace.api'
import { Route as WorkspaceAnalyticsRouteImport } from './routes/_workspace.analytics'
import { Route as WorkspaceAgentsRouteImport } from './routes/_workspace.agents'
import { Route as WorkspaceAdminRouteImport } from './routes/_workspace.admin'
import { Route as WorkspaceContactsContactIdRouteImport } from './routes/_workspace.contacts.$contactId'

const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const LogoutRoute = LogoutRouteImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CallbackRoute = CallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceRoute = WorkspaceRouteImport.update({
  id: '/_workspace',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceWorkflowsRoute = WorkspaceWorkflowsRouteImport.update({
  id: '/workflows',
  path: '/workflows',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceStatesRoute = WorkspaceStatesRouteImport.update({
  id: '/states',
  path: '/states',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceSourcesRoute = WorkspaceSourcesRouteImport.update({
  id: '/sources',
  path: '/sources',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceSettingsRoute = WorkspaceSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceRunsRoute = WorkspaceRunsRouteImport.update({
  id: '/runs',
  path: '/runs',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceReportsRoute = WorkspaceReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceOnboardingRoute = WorkspaceOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceNotificationsRoute = WorkspaceNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceLegalRoute = WorkspaceLegalRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceKanbanRoute = WorkspaceKanbanRouteImport.update({
  id: '/kanban',
  path: '/kanban',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceIntegrationsRoute = WorkspaceIntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceInboxRoute = WorkspaceInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceHealthRoute = WorkspaceHealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceFormsRoute = WorkspaceFormsRouteImport.update({
  id: '/forms',
  path: '/forms',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceDocumentsRoute = WorkspaceDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceDataMapRoute = WorkspaceDataMapRouteImport.update({
  id: '/data-map',
  path: '/data-map',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceDataLifecycleRoute = WorkspaceDataLifecycleRouteImport.update({
  id: '/data-lifecycle',
  path: '/data-lifecycle',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceContactsRoute = WorkspaceContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceConnectionsRoute = WorkspaceConnectionsRouteImport.update({
  id: '/connections',
  path: '/connections',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceClientsRoute = WorkspaceClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceCapabilitiesRoute = WorkspaceCapabilitiesRouteImport.update({
  id: '/capabilities',
  path: '/capabilities',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceBrainRoute = WorkspaceBrainRouteImport.update({
  id: '/brain',
  path: '/brain',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceBillingRoute = WorkspaceBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceApiRoute = WorkspaceApiRouteImport.update({
  id: '/api',
  path: '/api',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceAnalyticsRoute = WorkspaceAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceAgentsRoute = WorkspaceAgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceAdminRoute = WorkspaceAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceContactsContactIdRoute =
  WorkspaceContactsContactIdRouteImport.update({
    id: '/$contactId',
    path: '/$contactId',
    getParentRoute: () => WorkspaceContactsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/callback': typeof CallbackRoute
  '/dashboard': typeof DashboardRoute
  '/logout': typeof LogoutRoute
  '/sign-in': typeof SignInRoute
  '/admin': typeof WorkspaceAdminRoute
  '/agents': typeof WorkspaceAgentsRoute
  '/analytics': typeof WorkspaceAnalyticsRoute
  '/api': typeof WorkspaceApiRoute
  '/billing': typeof WorkspaceBillingRoute
  '/brain': typeof WorkspaceBrainRoute
  '/capabilities': typeof WorkspaceCapabilitiesRoute
  '/clients': typeof WorkspaceClientsRoute
  '/connections': typeof WorkspaceConnectionsRoute
  '/contacts': typeof WorkspaceContactsRouteWithChildren
  '/data-lifecycle': typeof WorkspaceDataLifecycleRoute
  '/data-map': typeof WorkspaceDataMapRoute
  '/documents': typeof WorkspaceDocumentsRoute
  '/forms': typeof WorkspaceFormsRoute
  '/health': typeof WorkspaceHealthRoute
  '/inbox': typeof WorkspaceInboxRoute
  '/integrations': typeof WorkspaceIntegrationsRoute
  '/kanban': typeof WorkspaceKanbanRoute
  '/legal': typeof WorkspaceLegalRoute
  '/notifications': typeof WorkspaceNotificationsRoute
  '/onboarding': typeof WorkspaceOnboardingRoute
  '/reports': typeof WorkspaceReportsRoute
  '/runs': typeof WorkspaceRunsRoute
  '/settings': typeof WorkspaceSettingsRoute
  '/sources': typeof WorkspaceSourcesRoute
  '/states': typeof WorkspaceStatesRoute
  '/workflows': typeof WorkspaceWorkflowsRoute
  '/contacts/$contactId': typeof WorkspaceContactsContactIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/callback': typeof CallbackRoute
  '/dashboard': typeof DashboardRoute
  '/logout': typeof LogoutRoute
  '/sign-in': typeof SignInRoute
  '/admin': typeof WorkspaceAdminRoute
  '/agents': typeof WorkspaceAgentsRoute
  '/analytics': typeof WorkspaceAnalyticsRoute
  '/api': typeof WorkspaceApiRoute
  '/billing': typeof WorkspaceBillingRoute
  '/brain': typeof WorkspaceBrainRoute
  '/capabilities': typeof WorkspaceCapabilitiesRoute
  '/clients': typeof WorkspaceClientsRoute
  '/connections': typeof WorkspaceConnectionsRoute
  '/contacts': typeof WorkspaceContactsRouteWithChildren
  '/data-lifecycle': typeof WorkspaceDataLifecycleRoute
  '/data-map': typeof WorkspaceDataMapRoute
  '/documents': typeof WorkspaceDocumentsRoute
  '/forms': typeof WorkspaceFormsRoute
  '/health': typeof WorkspaceHealthRoute
  '/inbox': typeof WorkspaceInboxRoute
  '/integrations': typeof WorkspaceIntegrationsRoute
  '/kanban': typeof WorkspaceKanbanRoute
  '/legal': typeof WorkspaceLegalRoute
  '/notifications': typeof WorkspaceNotificationsRoute
  '/onboarding': typeof WorkspaceOnboardingRoute
  '/reports': typeof WorkspaceReportsRoute
  '/runs': typeof WorkspaceRunsRoute
  '/settings': typeof WorkspaceSettingsRoute
  '/sources': typeof WorkspaceSourcesRoute
  '/states': typeof WorkspaceStatesRoute
  '/workflows': typeof WorkspaceWorkflowsRoute
  '/contacts/$contactId': typeof WorkspaceContactsContactIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_workspace': typeof WorkspaceRouteWithChildren
  '/callback': typeof CallbackRoute
  '/dashboard': typeof DashboardRoute
  '/logout': typeof LogoutRoute
  '/sign-in': typeof SignInRoute
  '/_workspace/admin': typeof WorkspaceAdminRoute
  '/_workspace/agents': typeof WorkspaceAgentsRoute
  '/_workspace/analytics': typeof WorkspaceAnalyticsRoute
  '/_workspace/api': typeof WorkspaceApiRoute
  '/_workspace/billing': typeof WorkspaceBillingRoute
  '/_workspace/brain': typeof WorkspaceBrainRoute
  '/_workspace/capabilities': typeof WorkspaceCapabilitiesRoute
  '/_workspace/clients': typeof WorkspaceClientsRoute
  '/_workspace/connections': typeof WorkspaceConnectionsRoute
  '/_workspace/contacts': typeof WorkspaceContactsRouteWithChildren
  '/_workspace/data-lifecycle': typeof WorkspaceDataLifecycleRoute
  '/_workspace/data-map': typeof WorkspaceDataMapRoute
  '/_workspace/documents': typeof WorkspaceDocumentsRoute
  '/_workspace/forms': typeof WorkspaceFormsRoute
  '/_workspace/health': typeof WorkspaceHealthRoute
  '/_workspace/inbox': typeof WorkspaceInboxRoute
  '/_workspace/integrations': typeof WorkspaceIntegrationsRoute
  '/_workspace/kanban': typeof WorkspaceKanbanRoute
  '/_workspace/legal': typeof WorkspaceLegalRoute
  '/_workspace/notifications': typeof WorkspaceNotificationsRoute
  '/_workspace/onboarding': typeof WorkspaceOnboardingRoute
  '/_workspace/reports': typeof WorkspaceReportsRoute
  '/_workspace/runs': typeof WorkspaceRunsRoute
  '/_workspace/settings': typeof WorkspaceSettingsRoute
  '/_workspace/sources': typeof WorkspaceSourcesRoute
  '/_workspace/states': typeof WorkspaceStatesRoute
  '/_workspace/workflows': typeof WorkspaceWorkflowsRoute
  '/_workspace/contacts/$contactId': typeof WorkspaceContactsContactIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/callback'
    | '/dashboard'
    | '/logout'
    | '/sign-in'
    | '/admin'
    | '/agents'
    | '/analytics'
    | '/api'
    | '/billing'
    | '/brain'
    | '/capabilities'
    | '/clients'
    | '/connections'
    | '/contacts'
    | '/data-lifecycle'
    | '/data-map'
    | '/documents'
    | '/forms'
    | '/health'
    | '/inbox'
    | '/integrations'
    | '/kanban'
    | '/legal'
    | '/notifications'
    | '/onboarding'
    | '/reports'
    | '/runs'
    | '/settings'
    | '/sources'
    | '/states'
    | '/workflows'
    | '/contacts/$contactId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/callback'
    | '/dashboard'
    | '/logout'
    | '/sign-in'
    | '/admin'
    | '/agents'
    | '/analytics'
    | '/api'
    | '/billing'
    | '/brain'
    | '/capabilities'
    | '/clients'
    | '/connections'
    | '/contacts'
    | '/data-lifecycle'
    | '/data-map'
    | '/documents'
    | '/forms'
    | '/health'
    | '/inbox'
    | '/integrations'
    | '/kanban'
    | '/legal'
    | '/notifications'
    | '/onboarding'
    | '/reports'
    | '/runs'
    | '/settings'
    | '/sources'
    | '/states'
    | '/workflows'
    | '/contacts/$contactId'
  id:
    | '__root__'
    | '/'
    | '/_workspace'
    | '/callback'
    | '/dashboard'
    | '/logout'
    | '/sign-in'
    | '/_workspace/admin'
    | '/_workspace/agents'
    | '/_workspace/analytics'
    | '/_workspace/api'
    | '/_workspace/billing'
    | '/_workspace/brain'
    | '/_workspace/capabilities'
    | '/_workspace/clients'
    | '/_workspace/connections'
    | '/_workspace/contacts'
    | '/_workspace/data-lifecycle'
    | '/_workspace/data-map'
    | '/_workspace/documents'
    | '/_workspace/forms'
    | '/_workspace/health'
    | '/_workspace/inbox'
    | '/_workspace/integrations'
    | '/_workspace/kanban'
    | '/_workspace/legal'
    | '/_workspace/notifications'
    | '/_workspace/onboarding'
    | '/_workspace/reports'
    | '/_workspace/runs'
    | '/_workspace/settings'
    | '/_workspace/sources'
    | '/_workspace/states'
    | '/_workspace/workflows'
    | '/_workspace/contacts/$contactId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  WorkspaceRoute: typeof WorkspaceRouteWithChildren
  CallbackRoute: typeof CallbackRoute
  DashboardRoute: typeof DashboardRoute
  LogoutRoute: typeof LogoutRoute
  SignInRoute: typeof SignInRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logout': {
      id: '/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof LogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/callback': {
      id: '/callback'
      path: '/callback'
      fullPath: '/callback'
      preLoaderRoute: typeof CallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_workspace': {
      id: '/_workspace'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof WorkspaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_workspace/workflows': {
      id: '/_workspace/workflows'
      path: '/workflows'
      fullPath: '/workflows'
      preLoaderRoute: typeof WorkspaceWorkflowsRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/_workspace/states': {
      id: '/_workspace/states'
      path: '/states'
      fullPath: '/states'
      preLoaderRoute: typeof WorkspaceStatesRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/_workspace/sources': {
      id: '/_workspace/sources'
      path: '/sources'
      fullPath: '/sources'
      preLoaderRoute: typeof WorkspaceSourcesRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/_workspace/settings': {
      id: '/_workspace/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof WorkspaceSettingsRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/_workspace/runs': {
      id: '/_workspace/runs'
      path: '/runs'
      fullPath: '/runs'
      preLoaderRoute: typeof WorkspaceRunsRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/_workspace/reports': {
      id: '/_workspace/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof WorkspaceReportsRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/_workspace/onboarding': {
      id: '/_workspace/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof WorkspaceOnboardingRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/_workspace/notifications': {
      id: '/_workspace/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof WorkspaceNotificationsRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/_workspace/legal': {
      id: '/_workspace/legal'
      path: '/legal'
      fullPath: '/legal'
      preLoaderRoute: typeof WorkspaceLegalRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/_workspace/kanban': {
      id: '/_workspace/kanban'
      path: '/kanban'
      fullPath: '/kanban'
      preLoaderRoute: typeof WorkspaceKanbanRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/_workspace/integrations': {
      id: '/_workspace/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof WorkspaceIntegrationsRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/_workspace/inbox': {
      id: '/_workspace/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof WorkspaceInboxRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/_workspace/health': {
      id: '/_workspace/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof WorkspaceHealthRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/_workspace/forms': {
      id: '/_workspace/forms'
      path: '/forms'
      fullPath: '/forms'
      preLoaderRoute: typeof WorkspaceFormsRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/_workspace/documents': {
      id: '/_workspace/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof WorkspaceDocumentsRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/_workspace/data-map': {
      id: '/_workspace/data-map'
      path: '/data-map'
      fullPath: '/data-map'
      preLoaderRoute: typeof WorkspaceDataMapRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/_workspace/data-lifecycle': {
      id: '/_workspace/data-lifecycle'
      path: '/data-lifecycle'
      fullPath: '/data-lifecycle'
      preLoaderRoute: typeof WorkspaceDataLifecycleRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/_workspace/contacts': {
      id: '/_workspace/contacts'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof WorkspaceContactsRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/_workspace/connections': {
      id: '/_workspace/connections'
      path: '/connections'
      fullPath: '/connections'
      preLoaderRoute: typeof WorkspaceConnectionsRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/_workspace/clients': {
      id: '/_workspace/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof WorkspaceClientsRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/_workspace/capabilities': {
      id: '/_workspace/capabilities'
      path: '/capabilities'
      fullPath: '/capabilities'
      preLoaderRoute: typeof WorkspaceCapabilitiesRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/_workspace/brain': {
      id: '/_workspace/brain'
      path: '/brain'
      fullPath: '/brain'
      preLoaderRoute: typeof WorkspaceBrainRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/_workspace/billing': {
      id: '/_workspace/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof WorkspaceBillingRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/_workspace/api': {
      id: '/_workspace/api'
      path: '/api'
      fullPath: '/api'
      preLoaderRoute: typeof WorkspaceApiRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/_workspace/analytics': {
      id: '/_workspace/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof WorkspaceAnalyticsRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/_workspace/agents': {
      id: '/_workspace/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof WorkspaceAgentsRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/_workspace/admin': {
      id: '/_workspace/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof WorkspaceAdminRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/_workspace/contacts/$contactId': {
      id: '/_workspace/contacts/$contactId'
      path: '/$contactId'
      fullPath: '/contacts/$contactId'
      preLoaderRoute: typeof WorkspaceContactsContactIdRouteImport
      parentRoute: typeof WorkspaceContactsRoute
    }
  }
}

interface WorkspaceContactsRouteChildren {
  WorkspaceContactsContactIdRoute: typeof WorkspaceContactsContactIdRoute
}

const WorkspaceContactsRouteChildren: WorkspaceContactsRouteChildren = {
  WorkspaceContactsContactIdRoute: WorkspaceContactsContactIdRoute,
}

const WorkspaceContactsRouteWithChildren =
  WorkspaceContactsRoute._addFileChildren(WorkspaceContactsRouteChildren)

interface WorkspaceRouteChildren {
  WorkspaceAdminRoute: typeof WorkspaceAdminRoute
  WorkspaceAgentsRoute: typeof WorkspaceAgentsRoute
  WorkspaceAnalyticsRoute: typeof WorkspaceAnalyticsRoute
  WorkspaceApiRoute: typeof WorkspaceApiRoute
  WorkspaceBillingRoute: typeof WorkspaceBillingRoute
  WorkspaceBrainRoute: typeof WorkspaceBrainRoute
  WorkspaceCapabilitiesRoute: typeof WorkspaceCapabilitiesRoute
  WorkspaceClientsRoute: typeof WorkspaceClientsRoute
  WorkspaceConnectionsRoute: typeof WorkspaceConnectionsRoute
  WorkspaceContactsRoute: typeof WorkspaceContactsRouteWithChildren
  WorkspaceDataLifecycleRoute: typeof WorkspaceDataLifecycleRoute
  WorkspaceDataMapRoute: typeof WorkspaceDataMapRoute
  WorkspaceDocumentsRoute: typeof WorkspaceDocumentsRoute
  WorkspaceFormsRoute: typeof WorkspaceFormsRoute
  WorkspaceHealthRoute: typeof WorkspaceHealthRoute
  WorkspaceInboxRoute: typeof WorkspaceInboxRoute
  WorkspaceIntegrationsRoute: typeof WorkspaceIntegrationsRoute
  WorkspaceKanbanRoute: typeof WorkspaceKanbanRoute
  WorkspaceLegalRoute: typeof WorkspaceLegalRoute
  WorkspaceNotificationsRoute: typeof WorkspaceNotificationsRoute
  WorkspaceOnboardingRoute: typeof WorkspaceOnboardingRoute
  WorkspaceReportsRoute: typeof WorkspaceReportsRoute
  WorkspaceRunsRoute: typeof WorkspaceRunsRoute
  WorkspaceSettingsRoute: typeof WorkspaceSettingsRoute
  WorkspaceSourcesRoute: typeof WorkspaceSourcesRoute
  WorkspaceStatesRoute: typeof WorkspaceStatesRoute
  WorkspaceWorkflowsRoute: typeof WorkspaceWorkflowsRoute
}

const WorkspaceRouteChildren: WorkspaceRouteChildren = {
  WorkspaceAdminRoute: WorkspaceAdminRoute,
  WorkspaceAgentsRoute: WorkspaceAgentsRoute,
  WorkspaceAnalyticsRoute: WorkspaceAnalyticsRoute,
  WorkspaceApiRoute: WorkspaceApiRoute,
  WorkspaceBillingRoute: WorkspaceBillingRoute,
  WorkspaceBrainRoute: WorkspaceBrainRoute,
  WorkspaceCapabilitiesRoute: WorkspaceCapabilitiesRoute,
  WorkspaceClientsRoute: WorkspaceClientsRoute,
  WorkspaceConnectionsRoute: WorkspaceConnectionsRoute,
  WorkspaceContactsRoute: WorkspaceContactsRouteWithChildren,
  WorkspaceDataLifecycleRoute: WorkspaceDataLifecycleRoute,
  WorkspaceDataMapRoute: WorkspaceDataMapRoute,
  WorkspaceDocumentsRoute: WorkspaceDocumentsRoute,
  WorkspaceFormsRoute: WorkspaceFormsRoute,
  WorkspaceHealthRoute: WorkspaceHealthRoute,
  WorkspaceInboxRoute: WorkspaceInboxRoute,
  WorkspaceIntegrationsRoute: WorkspaceIntegrationsRoute,
  WorkspaceKanbanRoute: WorkspaceKanbanRoute,
  WorkspaceLegalRoute: WorkspaceLegalRoute,
  WorkspaceNotificationsRoute: WorkspaceNotificationsRoute,
  WorkspaceOnboardingRoute: WorkspaceOnboardingRoute,
  WorkspaceReportsRoute: WorkspaceReportsRoute,
  WorkspaceRunsRoute: WorkspaceRunsRoute,
  WorkspaceSettingsRoute: WorkspaceSettingsRoute,
  WorkspaceSourcesRoute: WorkspaceSourcesRoute,
  WorkspaceStatesRoute: WorkspaceStatesRoute,
  WorkspaceWorkflowsRoute: WorkspaceWorkflowsRoute,
}

const WorkspaceRouteWithChildren = WorkspaceRoute._addFileChildren(
  WorkspaceRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  WorkspaceRoute: WorkspaceRouteWithChildren,
  CallbackRoute: CallbackRoute,
  DashboardRoute: DashboardRoute,
  LogoutRoute: LogoutRoute,
  SignInRoute: SignInRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
