/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkspaceOnboardingRouteImport } from './routes/_workspace.onboarding'
import { Route as WorkspaceNotificationsRouteImport } from './routes/_workspace.notifications'
import { Route as WorkspaceLegalRouteImport } from './routes/_workspace.legal'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceOnboardingRoute = WorkspaceOnboardingRouteImport.update({
  id: '/_workspace/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceNotificationsRoute = WorkspaceNotificationsRouteImport.update({
  id: '/_workspace/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceLegalRoute = WorkspaceLegalRouteImport.update({
  id: '/_workspace/legal',
  path: '/legal',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/legal': typeof WorkspaceLegalRoute
  '/notifications': typeof WorkspaceNotificationsRoute
  '/onboarding': typeof WorkspaceOnboardingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/legal': typeof WorkspaceLegalRoute
  '/notifications': typeof WorkspaceNotificationsRoute
  '/onboarding': typeof WorkspaceOnboardingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_workspace/legal': typeof WorkspaceLegalRoute
  '/_workspace/notifications': typeof WorkspaceNotificationsRoute
  '/_workspace/onboarding': typeof WorkspaceOnboardingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/legal' | '/notifications' | '/onboarding'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/legal' | '/notifications' | '/onboarding'
  id:
    | '__root__'
    | '/'
    | '/_workspace/legal'
    | '/_workspace/notifications'
    | '/_workspace/onboarding'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  WorkspaceLegalRoute: typeof WorkspaceLegalRoute
  WorkspaceNotificationsRoute: typeof WorkspaceNotificationsRoute
  WorkspaceOnboardingRoute: typeof WorkspaceOnboardingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_workspace/onboarding': {
      id: '/_workspace/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof WorkspaceOnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_workspace/notifications': {
      id: '/_workspace/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof WorkspaceNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_workspace/legal': {
      id: '/_workspace/legal'
      path: '/legal'
      fullPath: '/legal'
      preLoaderRoute: typeof WorkspaceLegalRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  WorkspaceLegalRoute: WorkspaceLegalRoute,
  WorkspaceNotificationsRoute: WorkspaceNotificationsRoute,
  WorkspaceOnboardingRoute: WorkspaceOnboardingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
