import {
  existsSync,
  lstatSync,
  mkdirSync,
  readFileSync,
  renameSync,
  writeFileSync,
} from "node:fs";
import { dirname, isAbsolute, join, resolve } from "node:path";
import { assembleMigrationRegistry } from "../confect/internal/migrationFragment";

const args = process.argv.slice(2);
const rootIndex = args.indexOf("--root");
const hasRoot = rootIndex >= 0;
const hasRootCwd = args.includes("--root-cwd");
const rootFromCwd = () => {
  const cwd = process.cwd();
  return cwd.endsWith("/packages/convex") ? dirname(dirname(cwd)) : cwd;
};
const repositoryRootFrom = (value: string) =>
  value.endsWith("/packages/convex") ? dirname(dirname(value)) : value;
const rootArg = hasRoot ? args[rootIndex + 1] : undefined;
const root = rootArg
  ? repositoryRootFrom(resolve(rootArg))
  : hasRootCwd
    ? rootFromCwd()
    : undefined;
const mode = args.includes("--write")
  ? "write"
  : args.includes("--check")
    ? "check"
    : undefined;
if (
  !root ||
  !isAbsolute(root) ||
  (hasRoot && (!rootArg || !isAbsolute(rootArg))) ||
  !mode ||
  (args.includes("--write") && args.includes("--check")) ||
  (hasRoot && hasRootCwd)
)
  throw new Error("usage: (--root <absolute>|--root-cwd) (--check|--write)");
const dir = join(root, "packages/convex/confect/internal/migration-fragments");
const target = join(
  root,
  "packages/convex/confect/internal/migrations.generated.ts",
);
const taskIds = ["S00-T04", "S01-T02", "S02-T01", "S02-T03", "S05-T01"];
const fragments = taskIds.map((taskId) =>
  readFileSync(join(dir, `${taskId}.json`), "utf8"),
);
const registry = assembleMigrationRegistry(fragments);
const bytes = `// @generated by scripts/generate-migration-registry.mts\nexport default ${registry.bytes}`;
try {
  if (lstatSync(target).isSymbolicLink())
    throw new Error("refuse to write registry symlink");
} catch (error) {
  if (
    error instanceof Error &&
    error.message === "refuse to write registry symlink"
  )
    throw error;
}
if (mode === "check") {
  if (!existsSync(target)) process.exit(0);
  if (readFileSync(target, "utf8") !== bytes)
    throw new Error("migration registry is stale");
  process.exit(0);
}
try {
  if (lstatSync(target).isSymbolicLink())
    throw new Error("refuse to write registry symlink");
} catch (error) {
  if (
    error instanceof Error &&
    error.message === "refuse to write registry symlink"
  )
    throw error;
}
mkdirSync(dirname(target), { recursive: true });
const tmp = `${target}.tmp-${process.pid}`;
writeFileSync(tmp, bytes);
renameSync(tmp, target);
if (readFileSync(target, "utf8") !== bytes)
  throw new Error("non-idempotent registry write");
