import type { Document } from "@confect/server";
import type schemaDefinition from "./schema";

export type AccessAuditEventsDoc = Document.Document<typeof schemaDefinition, "accessAuditEvents">;
export type ActionApprovalsDoc = Document.Document<typeof schemaDefinition, "actionApprovals">;
export type ActionDigestsDoc = Document.Document<typeof schemaDefinition, "actionDigests">;
export type ActionJobsDoc = Document.Document<typeof schemaDefinition, "actionJobs">;
export type ActionTriggersDoc = Document.Document<typeof schemaDefinition, "actionTriggers">;
export type ApiKeysDoc = Document.Document<typeof schemaDefinition, "apiKeys">;
export type BillingPlansDoc = Document.Document<typeof schemaDefinition, "billingPlans">;
export type BrainPagesDoc = Document.Document<typeof schemaDefinition, "brainPages">;
export type CitationsDoc = Document.Document<typeof schemaDefinition, "citations">;
export type ClaimsDoc = Document.Document<typeof schemaDefinition, "claims">;
export type ConceptsDoc = Document.Document<typeof schemaDefinition, "concepts">;
export type ContextPacksDoc = Document.Document<typeof schemaDefinition, "contextPacks">;
export type CreditLedgerDoc = Document.Document<typeof schemaDefinition, "creditLedger">;
export type DeployActionConsumptionsDoc = Document.Document<typeof schemaDefinition, "deployActionConsumptions">;
export type DeployApprovalsDoc = Document.Document<typeof schemaDefinition, "deployApprovals">;
export type DeployAuthorityAuditEventsDoc = Document.Document<typeof schemaDefinition, "deployAuthorityAuditEvents">;
export type DeployAuthorityIssuersDoc = Document.Document<typeof schemaDefinition, "deployAuthorityIssuers">;
export type DeployCensusSnapshotsDoc = Document.Document<typeof schemaDefinition, "deployCensusSnapshots">;
export type DeployVerdictsDoc = Document.Document<typeof schemaDefinition, "deployVerdicts">;
export type DocumentAnnotationsDoc = Document.Document<typeof schemaDefinition, "documentAnnotations">;
export type DocumentVersionsDoc = Document.Document<typeof schemaDefinition, "documentVersions">;
export type DocumentsDoc = Document.Document<typeof schemaDefinition, "documents">;
export type DsarRequestsDoc = Document.Document<typeof schemaDefinition, "dsarRequests">;
export type EmailCampaignsDoc = Document.Document<typeof schemaDefinition, "emailCampaigns">;
export type EmailDeliveriesDoc = Document.Document<typeof schemaDefinition, "emailDeliveries">;
export type EmailEventsDoc = Document.Document<typeof schemaDefinition, "emailEvents">;
export type EmailSubscribersDoc = Document.Document<typeof schemaDefinition, "emailSubscribers">;
export type EmailSuppressionsDoc = Document.Document<typeof schemaDefinition, "emailSuppressions">;
export type EntitlementsDoc = Document.Document<typeof schemaDefinition, "entitlements">;
export type FeatureFlagPoliciesDoc = Document.Document<typeof schemaDefinition, "featureFlagPolicies">;
export type InvitationsDoc = Document.Document<typeof schemaDefinition, "invitations">;
export type NotificationPreferencesDoc = Document.Document<typeof schemaDefinition, "notificationPreferences">;
export type NotificationRecordsDoc = Document.Document<typeof schemaDefinition, "notificationRecords">;
export type OrganizationMembersDoc = Document.Document<typeof schemaDefinition, "organizationMembers">;
export type OrganizationsDoc = Document.Document<typeof schemaDefinition, "organizations">;
export type PoliciesDoc = Document.Document<typeof schemaDefinition, "policies">;
export type PromptRegistryDoc = Document.Document<typeof schemaDefinition, "promptRegistry">;
export type RecordsDoc = Document.Document<typeof schemaDefinition, "records">;
export type ProviderConnectionsDoc = Document.Document<typeof schemaDefinition, "providerConnections">;
export type TransformBlocksDoc = Document.Document<typeof schemaDefinition, "transformBlocks">;
export type TransformDefinitionsDoc = Document.Document<typeof schemaDefinition, "transformDefinitions">;
export type TransformRunsDoc = Document.Document<typeof schemaDefinition, "transformRuns">;
export type UsageEventsDoc = Document.Document<typeof schemaDefinition, "usageEvents">;
export type UsersDoc = Document.Document<typeof schemaDefinition, "users">;
export type VersionFreshnessDoc = Document.Document<typeof schemaDefinition, "versionFreshness">;
export type VersionedEntriesDoc = Document.Document<typeof schemaDefinition, "versionedEntries">;
export type WebhookEventsDoc = Document.Document<typeof schemaDefinition, "webhookEvents">;
export type WorkspaceMembersDoc = Document.Document<typeof schemaDefinition, "workspaceMembers">;
export type WorkspacesDoc = Document.Document<typeof schemaDefinition, "workspaces">;

export interface Docs {
  accessAuditEvents: AccessAuditEventsDoc;
  actionApprovals: ActionApprovalsDoc;
  actionDigests: ActionDigestsDoc;
  actionJobs: ActionJobsDoc;
  actionTriggers: ActionTriggersDoc;
  apiKeys: ApiKeysDoc;
  billingPlans: BillingPlansDoc;
  brainPages: BrainPagesDoc;
  citations: CitationsDoc;
  claims: ClaimsDoc;
  concepts: ConceptsDoc;
  contextPacks: ContextPacksDoc;
  creditLedger: CreditLedgerDoc;
  deployActionConsumptions: DeployActionConsumptionsDoc;
  deployApprovals: DeployApprovalsDoc;
  deployAuthorityAuditEvents: DeployAuthorityAuditEventsDoc;
  deployAuthorityIssuers: DeployAuthorityIssuersDoc;
  deployCensusSnapshots: DeployCensusSnapshotsDoc;
  deployVerdicts: DeployVerdictsDoc;
  documentAnnotations: DocumentAnnotationsDoc;
  documentVersions: DocumentVersionsDoc;
  documents: DocumentsDoc;
  dsarRequests: DsarRequestsDoc;
  emailCampaigns: EmailCampaignsDoc;
  emailDeliveries: EmailDeliveriesDoc;
  emailEvents: EmailEventsDoc;
  emailSubscribers: EmailSubscribersDoc;
  emailSuppressions: EmailSuppressionsDoc;
  entitlements: EntitlementsDoc;
  featureFlagPolicies: FeatureFlagPoliciesDoc;
  invitations: InvitationsDoc;
  notificationPreferences: NotificationPreferencesDoc;
  notificationRecords: NotificationRecordsDoc;
  organizationMembers: OrganizationMembersDoc;
  organizations: OrganizationsDoc;
  policies: PoliciesDoc;
  promptRegistry: PromptRegistryDoc;
  records: RecordsDoc;
  providerConnections: ProviderConnectionsDoc;
  transformBlocks: TransformBlocksDoc;
  transformDefinitions: TransformDefinitionsDoc;
  transformRuns: TransformRunsDoc;
  usageEvents: UsageEventsDoc;
  users: UsersDoc;
  versionFreshness: VersionFreshnessDoc;
  versionedEntries: VersionedEntriesDoc;
  webhookEvents: WebhookEventsDoc;
  workspaceMembers: WorkspaceMembersDoc;
  workspaces: WorkspacesDoc;
}
