import type { Document } from "@confect/server";
import type schemaDefinition from "./schema";

export type AccessAuditEventsDoc = Document.Document<typeof schemaDefinition, "accessAuditEvents">;
export type ActionApprovalsDoc = Document.Document<typeof schemaDefinition, "actionApprovals">;
export type ActionDigestsDoc = Document.Document<typeof schemaDefinition, "actionDigests">;
export type ActionJobsDoc = Document.Document<typeof schemaDefinition, "actionJobs">;
export type ActionTriggersDoc = Document.Document<typeof schemaDefinition, "actionTriggers">;
export type ApiKeysDoc = Document.Document<typeof schemaDefinition, "apiKeys">;
export type BillingPlansDoc = Document.Document<typeof schemaDefinition, "billingPlans">;
export type BrainCorpusHealthDoc = Document.Document<typeof schemaDefinition, "brainCorpusHealth">;
export type BrainExportJobsDoc = Document.Document<typeof schemaDefinition, "brainExportJobs">;
export type BrainFeedbackReportsDoc = Document.Document<typeof schemaDefinition, "brainFeedbackReports">;
export type BrainMaintenanceProposalItemsDoc = Document.Document<typeof schemaDefinition, "brainMaintenanceProposalItems">;
export type BrainMaintenanceProposalsDoc = Document.Document<typeof schemaDefinition, "brainMaintenanceProposals">;
export type BrainOperationReceiptsDoc = Document.Document<typeof schemaDefinition, "brainOperationReceipts">;
export type BrainPageAuditEventsDoc = Document.Document<typeof schemaDefinition, "brainPageAuditEvents">;
export type BrainPagesDoc = Document.Document<typeof schemaDefinition, "brainPages">;
export type BrainProjectionPopulationDoc = Document.Document<typeof schemaDefinition, "brainProjectionPopulation">;
export type BrainProjectionValidationReceiptsDoc = Document.Document<typeof schemaDefinition, "brainProjectionValidationReceipts">;
export type BrainPublicationPausesDoc = Document.Document<typeof schemaDefinition, "brainPublicationPauses">;
export type BrainPublicationWorkerLeasesDoc = Document.Document<typeof schemaDefinition, "brainPublicationWorkerLeases">;
export type BrainReadModesDoc = Document.Document<typeof schemaDefinition, "brainReadModes">;
export type BrainRequiredScopeIntentsDoc = Document.Document<typeof schemaDefinition, "brainRequiredScopeIntents">;
export type BrainSourcesDoc = Document.Document<typeof schemaDefinition, "brainSources">;
export type CallRouteMappingsDoc = Document.Document<typeof schemaDefinition, "callRouteMappings">;
export type CallRoutingProposalsDoc = Document.Document<typeof schemaDefinition, "callRoutingProposals">;
export type ChannelDeliveryPoliciesDoc = Document.Document<typeof schemaDefinition, "channelDeliveryPolicies">;
export type ChannelRoutingPoliciesDoc = Document.Document<typeof schemaDefinition, "channelRoutingPolicies">;
export type ChannelSyncStatesDoc = Document.Document<typeof schemaDefinition, "channelSyncStates">;
export type CitationsDoc = Document.Document<typeof schemaDefinition, "citations">;
export type ClaimsDoc = Document.Document<typeof schemaDefinition, "claims">;
export type ClassificationDecisionsDoc = Document.Document<typeof schemaDefinition, "classificationDecisions">;
export type ConceptsDoc = Document.Document<typeof schemaDefinition, "concepts">;
export type ConnectorAllowlistGenerationsDoc = Document.Document<typeof schemaDefinition, "connectorAllowlistGenerations">;
export type ConnectorIncrementalCursorsDoc = Document.Document<typeof schemaDefinition, "connectorIncrementalCursors">;
export type ConnectorPageChunksDoc = Document.Document<typeof schemaDefinition, "connectorPageChunks">;
export type ConnectorPageEnvelopesDoc = Document.Document<typeof schemaDefinition, "connectorPageEnvelopes">;
export type ConnectorReconciliationRunsDoc = Document.Document<typeof schemaDefinition, "connectorReconciliationRuns">;
export type ConnectorReconciliationSeenDoc = Document.Document<typeof schemaDefinition, "connectorReconciliationSeen">;
export type ConnectorScopesDoc = Document.Document<typeof schemaDefinition, "connectorScopes">;
export type ConnectorSyncStatesDoc = Document.Document<typeof schemaDefinition, "connectorSyncStates">;
export type ContextPacksDoc = Document.Document<typeof schemaDefinition, "contextPacks">;
export type CreditLedgerDoc = Document.Document<typeof schemaDefinition, "creditLedger">;
export type DocumentAnnotationsDoc = Document.Document<typeof schemaDefinition, "documentAnnotations">;
export type DocumentSourceMembershipEdgesDoc = Document.Document<typeof schemaDefinition, "documentSourceMembershipEdges">;
export type DocumentSourceObjectsDoc = Document.Document<typeof schemaDefinition, "documentSourceObjects">;
export type DocumentSourceObservationsDoc = Document.Document<typeof schemaDefinition, "documentSourceObservations">;
export type DocumentSourceOutcomesDoc = Document.Document<typeof schemaDefinition, "documentSourceOutcomes">;
export type DocumentSourcePassagesDoc = Document.Document<typeof schemaDefinition, "documentSourcePassages">;
export type DocumentSourceRevisionsDoc = Document.Document<typeof schemaDefinition, "documentSourceRevisions">;
export type DocumentSourceScopePointersDoc = Document.Document<typeof schemaDefinition, "documentSourceScopePointers">;
export type DocumentVersionsDoc = Document.Document<typeof schemaDefinition, "documentVersions">;
export type DocumentsDoc = Document.Document<typeof schemaDefinition, "documents">;
export type DriveScopeConfigurationsDoc = Document.Document<typeof schemaDefinition, "driveScopeConfigurations">;
export type DsarRequestsDoc = Document.Document<typeof schemaDefinition, "dsarRequests">;
export type EntitlementsDoc = Document.Document<typeof schemaDefinition, "entitlements">;
export type FeatureFlagPoliciesDoc = Document.Document<typeof schemaDefinition, "featureFlagPolicies">;
export type IngestionObligationRepairEffectsDoc = Document.Document<typeof schemaDefinition, "ingestionObligationRepairEffects">;
export type IngestionObligationsDoc = Document.Document<typeof schemaDefinition, "ingestionObligations">;
export type InvitationsDoc = Document.Document<typeof schemaDefinition, "invitations">;
export type MigrationReceiptsDoc = Document.Document<typeof schemaDefinition, "migrationReceipts">;
export type MigrationRunsDoc = Document.Document<typeof schemaDefinition, "migrationRuns">;
export type ModelCallReceiptsDoc = Document.Document<typeof schemaDefinition, "modelCallReceipts">;
export type NotificationPreferencesDoc = Document.Document<typeof schemaDefinition, "notificationPreferences">;
export type NotificationRecordsDoc = Document.Document<typeof schemaDefinition, "notificationRecords">;
export type OrganizationMembersDoc = Document.Document<typeof schemaDefinition, "organizationMembers">;
export type OrganizationsDoc = Document.Document<typeof schemaDefinition, "organizations">;
export type OutboundDeliveryOutboxDoc = Document.Document<typeof schemaDefinition, "outboundDeliveryOutbox">;
export type PageRevisionsDoc = Document.Document<typeof schemaDefinition, "pageRevisions">;
export type PoliciesDoc = Document.Document<typeof schemaDefinition, "policies">;
export type PromptRegistryDoc = Document.Document<typeof schemaDefinition, "promptRegistry">;
export type ProviderConnectionsDoc = Document.Document<typeof schemaDefinition, "providerConnections">;
export type ProviderEventReceiptsDoc = Document.Document<typeof schemaDefinition, "providerEventReceipts">;
export type ProviderTargetResolutionIntentsDoc = Document.Document<typeof schemaDefinition, "providerTargetResolutionIntents">;
export type RetrievalEligibilityFencesDoc = Document.Document<typeof schemaDefinition, "retrievalEligibilityFences">;
export type RetrievalEntriesDoc = Document.Document<typeof schemaDefinition, "retrievalEntries">;
export type RetrievalPublicationJobsDoc = Document.Document<typeof schemaDefinition, "retrievalPublicationJobs">;
export type RetrievalPublicationSetsDoc = Document.Document<typeof schemaDefinition, "retrievalPublicationSets">;
export type RetrievalPublicationSubjectsDoc = Document.Document<typeof schemaDefinition, "retrievalPublicationSubjects">;
export type RetrievalRebuildChildrenDoc = Document.Document<typeof schemaDefinition, "retrievalRebuildChildren">;
export type RetrievalRebuildRunsDoc = Document.Document<typeof schemaDefinition, "retrievalRebuildRuns">;
export type RetrievalTokenCatalogDoc = Document.Document<typeof schemaDefinition, "retrievalTokenCatalog">;
export type RetrievalTokensDoc = Document.Document<typeof schemaDefinition, "retrievalTokens">;
export type ServicePrincipalsDoc = Document.Document<typeof schemaDefinition, "servicePrincipals">;
export type SlackIdentityBindingsDoc = Document.Document<typeof schemaDefinition, "slackIdentityBindings">;
export type SlackPublicationTargetIntentsDoc = Document.Document<typeof schemaDefinition, "slackPublicationTargetIntents">;
export type SlackQuestionReceiptsDoc = Document.Document<typeof schemaDefinition, "slackQuestionReceipts">;
export type SourceArtifactsDoc = Document.Document<typeof schemaDefinition, "sourceArtifacts">;
export type SourceChannelsDoc = Document.Document<typeof schemaDefinition, "sourceChannels">;
export type SourceProcessingJobsDoc = Document.Document<typeof schemaDefinition, "sourceProcessingJobs">;
export type SourceRevisionsDoc = Document.Document<typeof schemaDefinition, "sourceRevisions">;
export type SourceSegmentsDoc = Document.Document<typeof schemaDefinition, "sourceSegments">;
export type SourceUnitRevisionsDoc = Document.Document<typeof schemaDefinition, "sourceUnitRevisions">;
export type SourceUnitsDoc = Document.Document<typeof schemaDefinition, "sourceUnits">;
export type StructuredQueryFieldRegistrationsDoc = Document.Document<typeof schemaDefinition, "structuredQueryFieldRegistrations">;
export type StructuredSourceEntitiesDoc = Document.Document<typeof schemaDefinition, "structuredSourceEntities">;
export type StructuredSourceFieldsDoc = Document.Document<typeof schemaDefinition, "structuredSourceFields">;
export type StructuredSourceObservationsDoc = Document.Document<typeof schemaDefinition, "structuredSourceObservations">;
export type StructuredSourceRevisionsDoc = Document.Document<typeof schemaDefinition, "structuredSourceRevisions">;
export type StructuredSourceRoutesDoc = Document.Document<typeof schemaDefinition, "structuredSourceRoutes">;
export type TranscriptRevisionOrderMigrationItemsDoc = Document.Document<typeof schemaDefinition, "transcriptRevisionOrderMigrationItems">;
export type TranscriptRevisionOrderMigrationsDoc = Document.Document<typeof schemaDefinition, "transcriptRevisionOrderMigrations">;
export type TransformBlocksDoc = Document.Document<typeof schemaDefinition, "transformBlocks">;
export type TransformDefinitionsDoc = Document.Document<typeof schemaDefinition, "transformDefinitions">;
export type TransformRunsDoc = Document.Document<typeof schemaDefinition, "transformRuns">;
export type UsageEventsDoc = Document.Document<typeof schemaDefinition, "usageEvents">;
export type UsersDoc = Document.Document<typeof schemaDefinition, "users">;
export type VersionFreshnessDoc = Document.Document<typeof schemaDefinition, "versionFreshness">;
export type VersionedEntriesDoc = Document.Document<typeof schemaDefinition, "versionedEntries">;
export type WebhookEventsDoc = Document.Document<typeof schemaDefinition, "webhookEvents">;
export type WorkflowRunContextManifestsDoc = Document.Document<typeof schemaDefinition, "workflowRunContextManifests">;
export type WorkflowRunEventsDoc = Document.Document<typeof schemaDefinition, "workflowRunEvents">;
export type WorkflowRunEvidenceSnapshotsDoc = Document.Document<typeof schemaDefinition, "workflowRunEvidenceSnapshots">;
export type WorkflowRunLinksDoc = Document.Document<typeof schemaDefinition, "workflowRunLinks">;
export type WorkflowRunsDoc = Document.Document<typeof schemaDefinition, "workflowRuns">;
export type WorkflowStageRunsDoc = Document.Document<typeof schemaDefinition, "workflowStageRuns">;
export type WorkspaceMembersDoc = Document.Document<typeof schemaDefinition, "workspaceMembers">;
export type WorkspacesDoc = Document.Document<typeof schemaDefinition, "workspaces">;

export interface Docs {
  accessAuditEvents: AccessAuditEventsDoc;
  actionApprovals: ActionApprovalsDoc;
  actionDigests: ActionDigestsDoc;
  actionJobs: ActionJobsDoc;
  actionTriggers: ActionTriggersDoc;
  apiKeys: ApiKeysDoc;
  billingPlans: BillingPlansDoc;
  brainCorpusHealth: BrainCorpusHealthDoc;
  brainExportJobs: BrainExportJobsDoc;
  brainFeedbackReports: BrainFeedbackReportsDoc;
  brainMaintenanceProposalItems: BrainMaintenanceProposalItemsDoc;
  brainMaintenanceProposals: BrainMaintenanceProposalsDoc;
  brainOperationReceipts: BrainOperationReceiptsDoc;
  brainPageAuditEvents: BrainPageAuditEventsDoc;
  brainPages: BrainPagesDoc;
  brainProjectionPopulation: BrainProjectionPopulationDoc;
  brainProjectionValidationReceipts: BrainProjectionValidationReceiptsDoc;
  brainPublicationPauses: BrainPublicationPausesDoc;
  brainPublicationWorkerLeases: BrainPublicationWorkerLeasesDoc;
  brainReadModes: BrainReadModesDoc;
  brainRequiredScopeIntents: BrainRequiredScopeIntentsDoc;
  brainSources: BrainSourcesDoc;
  callRouteMappings: CallRouteMappingsDoc;
  callRoutingProposals: CallRoutingProposalsDoc;
  channelDeliveryPolicies: ChannelDeliveryPoliciesDoc;
  channelRoutingPolicies: ChannelRoutingPoliciesDoc;
  channelSyncStates: ChannelSyncStatesDoc;
  citations: CitationsDoc;
  claims: ClaimsDoc;
  classificationDecisions: ClassificationDecisionsDoc;
  concepts: ConceptsDoc;
  connectorAllowlistGenerations: ConnectorAllowlistGenerationsDoc;
  connectorIncrementalCursors: ConnectorIncrementalCursorsDoc;
  connectorPageChunks: ConnectorPageChunksDoc;
  connectorPageEnvelopes: ConnectorPageEnvelopesDoc;
  connectorReconciliationRuns: ConnectorReconciliationRunsDoc;
  connectorReconciliationSeen: ConnectorReconciliationSeenDoc;
  connectorScopes: ConnectorScopesDoc;
  connectorSyncStates: ConnectorSyncStatesDoc;
  contextPacks: ContextPacksDoc;
  creditLedger: CreditLedgerDoc;
  documentAnnotations: DocumentAnnotationsDoc;
  documentSourceMembershipEdges: DocumentSourceMembershipEdgesDoc;
  documentSourceObjects: DocumentSourceObjectsDoc;
  documentSourceObservations: DocumentSourceObservationsDoc;
  documentSourceOutcomes: DocumentSourceOutcomesDoc;
  documentSourcePassages: DocumentSourcePassagesDoc;
  documentSourceRevisions: DocumentSourceRevisionsDoc;
  documentSourceScopePointers: DocumentSourceScopePointersDoc;
  documentVersions: DocumentVersionsDoc;
  documents: DocumentsDoc;
  driveScopeConfigurations: DriveScopeConfigurationsDoc;
  dsarRequests: DsarRequestsDoc;
  entitlements: EntitlementsDoc;
  featureFlagPolicies: FeatureFlagPoliciesDoc;
  ingestionObligationRepairEffects: IngestionObligationRepairEffectsDoc;
  ingestionObligations: IngestionObligationsDoc;
  invitations: InvitationsDoc;
  migrationReceipts: MigrationReceiptsDoc;
  migrationRuns: MigrationRunsDoc;
  modelCallReceipts: ModelCallReceiptsDoc;
  notificationPreferences: NotificationPreferencesDoc;
  notificationRecords: NotificationRecordsDoc;
  organizationMembers: OrganizationMembersDoc;
  organizations: OrganizationsDoc;
  outboundDeliveryOutbox: OutboundDeliveryOutboxDoc;
  pageRevisions: PageRevisionsDoc;
  policies: PoliciesDoc;
  promptRegistry: PromptRegistryDoc;
  providerConnections: ProviderConnectionsDoc;
  providerEventReceipts: ProviderEventReceiptsDoc;
  providerTargetResolutionIntents: ProviderTargetResolutionIntentsDoc;
  retrievalEligibilityFences: RetrievalEligibilityFencesDoc;
  retrievalEntries: RetrievalEntriesDoc;
  retrievalPublicationJobs: RetrievalPublicationJobsDoc;
  retrievalPublicationSets: RetrievalPublicationSetsDoc;
  retrievalPublicationSubjects: RetrievalPublicationSubjectsDoc;
  retrievalRebuildChildren: RetrievalRebuildChildrenDoc;
  retrievalRebuildRuns: RetrievalRebuildRunsDoc;
  retrievalTokenCatalog: RetrievalTokenCatalogDoc;
  retrievalTokens: RetrievalTokensDoc;
  servicePrincipals: ServicePrincipalsDoc;
  slackIdentityBindings: SlackIdentityBindingsDoc;
  slackPublicationTargetIntents: SlackPublicationTargetIntentsDoc;
  slackQuestionReceipts: SlackQuestionReceiptsDoc;
  sourceArtifacts: SourceArtifactsDoc;
  sourceChannels: SourceChannelsDoc;
  sourceProcessingJobs: SourceProcessingJobsDoc;
  sourceRevisions: SourceRevisionsDoc;
  sourceSegments: SourceSegmentsDoc;
  sourceUnitRevisions: SourceUnitRevisionsDoc;
  sourceUnits: SourceUnitsDoc;
  structuredQueryFieldRegistrations: StructuredQueryFieldRegistrationsDoc;
  structuredSourceEntities: StructuredSourceEntitiesDoc;
  structuredSourceFields: StructuredSourceFieldsDoc;
  structuredSourceObservations: StructuredSourceObservationsDoc;
  structuredSourceRevisions: StructuredSourceRevisionsDoc;
  structuredSourceRoutes: StructuredSourceRoutesDoc;
  transcriptRevisionOrderMigrationItems: TranscriptRevisionOrderMigrationItemsDoc;
  transcriptRevisionOrderMigrations: TranscriptRevisionOrderMigrationsDoc;
  transformBlocks: TransformBlocksDoc;
  transformDefinitions: TransformDefinitionsDoc;
  transformRuns: TransformRunsDoc;
  usageEvents: UsageEventsDoc;
  users: UsersDoc;
  versionFreshness: VersionFreshnessDoc;
  versionedEntries: VersionedEntriesDoc;
  webhookEvents: WebhookEventsDoc;
  workflowRunContextManifests: WorkflowRunContextManifestsDoc;
  workflowRunEvents: WorkflowRunEventsDoc;
  workflowRunEvidenceSnapshots: WorkflowRunEvidenceSnapshotsDoc;
  workflowRunLinks: WorkflowRunLinksDoc;
  workflowRuns: WorkflowRunsDoc;
  workflowStageRuns: WorkflowStageRunsDoc;
  workspaceMembers: WorkspaceMembersDoc;
  workspaces: WorkspacesDoc;
}
