import type { Document } from "@confect/server";
import type schemaDefinition from "./schema";

export type AccessAuditEventsDoc = Document.Document<typeof schemaDefinition, "accessAuditEvents">;
export type ActionApprovalsDoc = Document.Document<typeof schemaDefinition, "actionApprovals">;
export type ActionDigestsDoc = Document.Document<typeof schemaDefinition, "actionDigests">;
export type ActionJobsDoc = Document.Document<typeof schemaDefinition, "actionJobs">;
export type ActionTriggersDoc = Document.Document<typeof schemaDefinition, "actionTriggers">;
export type ApiKeysDoc = Document.Document<typeof schemaDefinition, "apiKeys">;
export type BillingPlansDoc = Document.Document<typeof schemaDefinition, "billingPlans">;
export type BrainMaintenanceProposalsDoc = Document.Document<typeof schemaDefinition, "brainMaintenanceProposals">;
export type BrainPageAuditEventsDoc = Document.Document<typeof schemaDefinition, "brainPageAuditEvents">;
export type BrainPagesDoc = Document.Document<typeof schemaDefinition, "brainPages">;
export type BrainSourcesDoc = Document.Document<typeof schemaDefinition, "brainSources">;
export type ChannelDeliveryPoliciesDoc = Document.Document<typeof schemaDefinition, "channelDeliveryPolicies">;
export type ChannelRoutingPoliciesDoc = Document.Document<typeof schemaDefinition, "channelRoutingPolicies">;
export type ChannelSyncStatesDoc = Document.Document<typeof schemaDefinition, "channelSyncStates">;
export type CitationsDoc = Document.Document<typeof schemaDefinition, "citations">;
export type ClaimsDoc = Document.Document<typeof schemaDefinition, "claims">;
export type ClassificationDecisionsDoc = Document.Document<typeof schemaDefinition, "classificationDecisions">;
export type ConceptsDoc = Document.Document<typeof schemaDefinition, "concepts">;
export type ContextPacksDoc = Document.Document<typeof schemaDefinition, "contextPacks">;
export type CreditLedgerDoc = Document.Document<typeof schemaDefinition, "creditLedger">;
export type DocumentAnnotationsDoc = Document.Document<typeof schemaDefinition, "documentAnnotations">;
export type DocumentVersionsDoc = Document.Document<typeof schemaDefinition, "documentVersions">;
export type DocumentsDoc = Document.Document<typeof schemaDefinition, "documents">;
export type DsarRequestsDoc = Document.Document<typeof schemaDefinition, "dsarRequests">;
export type EntitlementsDoc = Document.Document<typeof schemaDefinition, "entitlements">;
export type FeatureFlagPoliciesDoc = Document.Document<typeof schemaDefinition, "featureFlagPolicies">;
export type InvitationsDoc = Document.Document<typeof schemaDefinition, "invitations">;
export type MigrationReceiptsDoc = Document.Document<typeof schemaDefinition, "migrationReceipts">;
export type MigrationRunsDoc = Document.Document<typeof schemaDefinition, "migrationRuns">;
export type ModelCallReceiptsDoc = Document.Document<typeof schemaDefinition, "modelCallReceipts">;
export type NotificationPreferencesDoc = Document.Document<typeof schemaDefinition, "notificationPreferences">;
export type NotificationRecordsDoc = Document.Document<typeof schemaDefinition, "notificationRecords">;
export type OrganizationMembersDoc = Document.Document<typeof schemaDefinition, "organizationMembers">;
export type OrganizationsDoc = Document.Document<typeof schemaDefinition, "organizations">;
export type OutboundDeliveryOutboxDoc = Document.Document<typeof schemaDefinition, "outboundDeliveryOutbox">;
export type PageRevisionsDoc = Document.Document<typeof schemaDefinition, "pageRevisions">;
export type PoliciesDoc = Document.Document<typeof schemaDefinition, "policies">;
export type PromptRegistryDoc = Document.Document<typeof schemaDefinition, "promptRegistry">;
export type ProviderConnectionsDoc = Document.Document<typeof schemaDefinition, "providerConnections">;
export type ProviderEventReceiptsDoc = Document.Document<typeof schemaDefinition, "providerEventReceipts">;
export type ServicePrincipalsDoc = Document.Document<typeof schemaDefinition, "servicePrincipals">;
export type SlackIdentityBindingsDoc = Document.Document<typeof schemaDefinition, "slackIdentityBindings">;
export type SlackQuestionReceiptsDoc = Document.Document<typeof schemaDefinition, "slackQuestionReceipts">;
export type SourceArtifactsDoc = Document.Document<typeof schemaDefinition, "sourceArtifacts">;
export type SourceChannelsDoc = Document.Document<typeof schemaDefinition, "sourceChannels">;
export type SourceProcessingJobsDoc = Document.Document<typeof schemaDefinition, "sourceProcessingJobs">;
export type SourceRevisionsDoc = Document.Document<typeof schemaDefinition, "sourceRevisions">;
export type TransformBlocksDoc = Document.Document<typeof schemaDefinition, "transformBlocks">;
export type TransformDefinitionsDoc = Document.Document<typeof schemaDefinition, "transformDefinitions">;
export type TransformRunsDoc = Document.Document<typeof schemaDefinition, "transformRuns">;
export type UsageEventsDoc = Document.Document<typeof schemaDefinition, "usageEvents">;
export type UsersDoc = Document.Document<typeof schemaDefinition, "users">;
export type VersionFreshnessDoc = Document.Document<typeof schemaDefinition, "versionFreshness">;
export type VersionedEntriesDoc = Document.Document<typeof schemaDefinition, "versionedEntries">;
export type WebhookEventsDoc = Document.Document<typeof schemaDefinition, "webhookEvents">;
export type WorkflowRunContextManifestsDoc = Document.Document<typeof schemaDefinition, "workflowRunContextManifests">;
export type WorkflowRunEventsDoc = Document.Document<typeof schemaDefinition, "workflowRunEvents">;
export type WorkflowRunEvidenceSnapshotsDoc = Document.Document<typeof schemaDefinition, "workflowRunEvidenceSnapshots">;
export type WorkflowRunLinksDoc = Document.Document<typeof schemaDefinition, "workflowRunLinks">;
export type WorkflowRunsDoc = Document.Document<typeof schemaDefinition, "workflowRuns">;
export type WorkflowStageRunsDoc = Document.Document<typeof schemaDefinition, "workflowStageRuns">;
export type WorkspaceMembersDoc = Document.Document<typeof schemaDefinition, "workspaceMembers">;
export type WorkspacesDoc = Document.Document<typeof schemaDefinition, "workspaces">;

export interface Docs {
  accessAuditEvents: AccessAuditEventsDoc;
  actionApprovals: ActionApprovalsDoc;
  actionDigests: ActionDigestsDoc;
  actionJobs: ActionJobsDoc;
  actionTriggers: ActionTriggersDoc;
  apiKeys: ApiKeysDoc;
  billingPlans: BillingPlansDoc;
  brainMaintenanceProposals: BrainMaintenanceProposalsDoc;
  brainPageAuditEvents: BrainPageAuditEventsDoc;
  brainPages: BrainPagesDoc;
  brainSources: BrainSourcesDoc;
  channelDeliveryPolicies: ChannelDeliveryPoliciesDoc;
  channelRoutingPolicies: ChannelRoutingPoliciesDoc;
  channelSyncStates: ChannelSyncStatesDoc;
  citations: CitationsDoc;
  claims: ClaimsDoc;
  classificationDecisions: ClassificationDecisionsDoc;
  concepts: ConceptsDoc;
  contextPacks: ContextPacksDoc;
  creditLedger: CreditLedgerDoc;
  documentAnnotations: DocumentAnnotationsDoc;
  documentVersions: DocumentVersionsDoc;
  documents: DocumentsDoc;
  dsarRequests: DsarRequestsDoc;
  entitlements: EntitlementsDoc;
  featureFlagPolicies: FeatureFlagPoliciesDoc;
  invitations: InvitationsDoc;
  migrationReceipts: MigrationReceiptsDoc;
  migrationRuns: MigrationRunsDoc;
  modelCallReceipts: ModelCallReceiptsDoc;
  notificationPreferences: NotificationPreferencesDoc;
  notificationRecords: NotificationRecordsDoc;
  organizationMembers: OrganizationMembersDoc;
  organizations: OrganizationsDoc;
  outboundDeliveryOutbox: OutboundDeliveryOutboxDoc;
  pageRevisions: PageRevisionsDoc;
  policies: PoliciesDoc;
  promptRegistry: PromptRegistryDoc;
  providerConnections: ProviderConnectionsDoc;
  providerEventReceipts: ProviderEventReceiptsDoc;
  servicePrincipals: ServicePrincipalsDoc;
  slackIdentityBindings: SlackIdentityBindingsDoc;
  slackQuestionReceipts: SlackQuestionReceiptsDoc;
  sourceArtifacts: SourceArtifactsDoc;
  sourceChannels: SourceChannelsDoc;
  sourceProcessingJobs: SourceProcessingJobsDoc;
  sourceRevisions: SourceRevisionsDoc;
  transformBlocks: TransformBlocksDoc;
  transformDefinitions: TransformDefinitionsDoc;
  transformRuns: TransformRunsDoc;
  usageEvents: UsageEventsDoc;
  users: UsersDoc;
  versionFreshness: VersionFreshnessDoc;
  versionedEntries: VersionedEntriesDoc;
  webhookEvents: WebhookEventsDoc;
  workflowRunContextManifests: WorkflowRunContextManifestsDoc;
  workflowRunEvents: WorkflowRunEventsDoc;
  workflowRunEvidenceSnapshots: WorkflowRunEvidenceSnapshotsDoc;
  workflowRunLinks: WorkflowRunLinksDoc;
  workflowRuns: WorkflowRunsDoc;
  workflowStageRuns: WorkflowStageRunsDoc;
  workspaceMembers: WorkspaceMembersDoc;
  workspaces: WorkspacesDoc;
}
