// @generated by scripts/generate-migration-registry.mts
export default {
  fragments: [
    {
      attestation: null,
      implementationModule: "../migration-implementations/S00-T04",
      migrations: ["probe.expand", "probe.fail"],
      phase: "expand",
      taskId: "S00-T04",
    },
    {
      attestation: null,
      implementationModule: "../migration-implementations/S01-T02",
      migrations: [
        "stableTenant.organizationKeys.expand",
        "stableTenant.workspaceKeys.expand",
      ],
      phase: "expand",
      taskId: "S01-T02",
    },
    {
      attestation: "no_executable_registration",
      implementationModule: "../migration-implementations/S02-T01",
      migrations: [],
      phase: "expand",
      taskId: "S02-T01",
    },
    {
      attestation: "no_executable_registration",
      implementationModule: "../migration-implementations/S02-T03",
      migrations: [],
      phase: "backfill",
      taskId: "S02-T03",
    },
    {
      attestation: "new_tables_only",
      implementationModule: null,
      migrations: [],
      phase: "contract",
      taskId: "S05-T01",
    },
  ],
  schemaVersion: 1,
};
