// Generated by pnpm data-resources:generate. Do not edit directly.

// prettier-ignore
export const currentLifecycleResourceIds = [
  "accessAuditEvents",
  "actionApprovals",
  "actionDigests",
  "actionJobs",
  "actionTriggers",
  "apiKeys",
  "billingPlans",
  "brainConnectorRuns",
  "brainConnectorRunSeen",
  "brainEvaluationExamples",
  "brainEvidenceRevisions",
  "brainEvidenceSources",
  "brainPages",
  "brainRetrievalEntries",
  "brainRetrievalTokens",
  "citations",
  "claims",
  "concepts",
  "contextPacks",
  "creditLedger",
  "documentAnnotations",
  "documents",
  "documentVersions",
  "dsarRequests",
  "emailCampaigns",
  "emailDeliveries",
  "emailSubscribers",
  "entitlements",
  "featureFlagPolicies",
  "invitations",
  "notificationPreferences",
  "notificationRecords",
  "pageRevisions",
  "policies",
  "providerConnections",
  "records",
  "transformBlocks",
  "transformDefinitions",
  "transformRuns",
  "usageEvents",
  "versionedEntries",
  "versionFreshness",
  "webhookEvents",
  "workflowArtifacts",
  "workflowEffectReservations",
  "workflowEventInstances",
  "workflowRunContextManifests",
  "workflowRunEvents",
  "workflowRunEvidenceSnapshots",
  "workflowRunLinks",
  "workflowRuns",
  "workflowStageRuns",
  "workspaceMembers",
  "workspaces"
] as const;

// prettier-ignore
export const workspaceLifecycleResourcePlans = [
  {
    id: "accessAuditEvents",
    owner: "workspace",
    exportMode: "redacted-json",
    deleteMode: "retain-audit",
    detail: "accessAuditEvents is durable Access And Tenancy state governed by the canonical access-and-tenancy lifecycle."
  },
  {
    id: "actionApprovals",
    owner: "workspace",
    exportMode: "redacted-json",
    deleteMode: "retain-audit",
    detail: "actionApprovals is durable Action Automation state governed by the canonical action-automation lifecycle."
  },
  {
    id: "actionDigests",
    owner: "workspace",
    exportMode: "redacted-json",
    deleteMode: "retain-audit",
    detail: "actionDigests is durable Action Automation state governed by the canonical action-automation lifecycle."
  },
  {
    id: "actionJobs",
    owner: "workspace",
    exportMode: "json",
    deleteMode: "retain-audit",
    detail: "actionJobs is durable Action Automation state governed by the canonical action-automation lifecycle."
  },
  {
    id: "actionTriggers",
    owner: "workspace",
    exportMode: "json",
    deleteMode: "delete",
    detail: "actionTriggers is durable Action Automation state governed by the canonical action-automation lifecycle."
  },
  {
    id: "apiKeys",
    owner: "workspace",
    exportMode: "redacted-json",
    deleteMode: "redact",
    detail: "apiKeys is durable Access And Tenancy state governed by the canonical access-and-tenancy lifecycle."
  },
  {
    id: "billingPlans",
    owner: "workspace",
    exportMode: "json",
    deleteMode: "delete",
    detail: "billingPlans is durable Billing And Entitlements state governed by the canonical billing-and-entitlements lifecycle."
  },
  {
    id: "brainConnectorRuns",
    owner: "workspace",
    exportMode: "json",
    deleteMode: "delete",
    detail: "Workspace connector run state, optional provider-connection generation fence, bounded counts, failure codes, and successful scope-specific reconciliation receipts."
  },
  {
    id: "brainConnectorRunSeen",
    owner: "workspace",
    exportMode: "json",
    deleteMode: "delete",
    detail: "Append-only source observations used to reconcile one bounded connector run without inferring removals after failure."
  },
  {
    id: "brainEvaluationExamples",
    owner: "workspace",
    exportMode: "redacted-json",
    deleteMode: "delete",
    detail: "Explicitly saved Ask Maestro evaluation examples with bounded immutable source references and no copied evidence excerpts."
  },
  {
    id: "brainEvidenceRevisions",
    owner: "workspace",
    exportMode: "markdown",
    deleteMode: "delete",
    detail: "Immutable provider-neutral evidence revisions with optional hash-bound provider metadata used for exact cited source reopening and integrity verification."
  },
  {
    id: "brainEvidenceSources",
    owner: "workspace",
    exportMode: "json",
    deleteMode: "delete",
    detail: "Current provider-neutral source pointers, hash-bound provider metadata, generations, scope, freshness, and removal state."
  },
  {
    id: "brainPages",
    owner: "workspace",
    exportMode: "markdown",
    deleteMode: "delete",
    detail: "brainPages is durable Knowledge Brain state governed by the canonical knowledge-brain lifecycle."
  },
  {
    id: "brainRetrievalEntries",
    owner: "workspace",
    exportMode: "markdown",
    deleteMode: "delete",
    detail: "Bounded current and retired retrieval projections for provider-neutral evidence search."
  },
  {
    id: "brainRetrievalTokens",
    owner: "workspace",
    exportMode: "json",
    deleteMode: "delete",
    detail: "Bounded token postings derived from current evidence and replaced transactionally with retrieval entries."
  },
  {
    id: "citations",
    owner: "workspace",
    exportMode: "json",
    deleteMode: "delete",
    detail: "citations is durable Knowledge Brain state governed by the canonical knowledge-brain lifecycle."
  },
  {
    id: "claims",
    owner: "workspace",
    exportMode: "json",
    deleteMode: "delete",
    detail: "claims is durable Knowledge Brain state governed by the canonical knowledge-brain lifecycle."
  },
  {
    id: "concepts",
    owner: "workspace",
    exportMode: "json",
    deleteMode: "delete",
    detail: "concepts is durable Knowledge Brain state governed by the canonical knowledge-brain lifecycle."
  },
  {
    id: "contextPacks",
    owner: "workspace",
    exportMode: "json",
    deleteMode: "delete",
    detail: "contextPacks is durable Knowledge Brain state governed by the canonical knowledge-brain lifecycle."
  },
  {
    id: "creditLedger",
    owner: "workspace",
    exportMode: "json",
    deleteMode: "retain-audit",
    detail: "creditLedger is durable Billing And Entitlements state governed by the canonical billing-and-entitlements lifecycle."
  },
  {
    id: "documentAnnotations",
    owner: "workspace",
    exportMode: "json",
    deleteMode: "delete",
    detail: "documentAnnotations is durable Document Collaboration state governed by the canonical document-collaboration lifecycle."
  },
  {
    id: "documents",
    owner: "workspace",
    exportMode: "markdown",
    deleteMode: "delete",
    detail: "documents is durable Document Collaboration state governed by the canonical document-collaboration lifecycle."
  },
  {
    id: "documentVersions",
    owner: "workspace",
    exportMode: "json",
    deleteMode: "retain-audit",
    detail: "documentVersions is durable Document Collaboration state governed by the canonical document-collaboration lifecycle."
  },
  {
    id: "dsarRequests",
    owner: "workspace",
    exportMode: "redacted-json",
    deleteMode: "retain-audit",
    detail: "dsarRequests is durable Data Lifecycle state governed by the canonical data-lifecycle lifecycle."
  },
  {
    id: "emailCampaigns",
    owner: "workspace",
    exportMode: "redacted-json",
    deleteMode: "delete",
    detail: "Consent-based broadcast campaign content and aggregate delivery state."
  },
  {
    id: "emailDeliveries",
    owner: "workspace",
    exportMode: "redacted-json",
    deleteMode: "retain-audit",
    detail: "Idempotent transactional and broadcast recipient delivery state."
  },
  {
    id: "emailSubscribers",
    owner: "workspace",
    exportMode: "redacted-json",
    deleteMode: "redact",
    detail: "Workspace-scoped explicit marketing consent and unsubscribe state."
  },
  {
    id: "entitlements",
    owner: "workspace",
    exportMode: "json",
    deleteMode: "retain-audit",
    detail: "entitlements is durable Billing And Entitlements state governed by the canonical billing-and-entitlements lifecycle."
  },
  {
    id: "featureFlagPolicies",
    owner: "workspace",
    exportMode: "json",
    deleteMode: "delete",
    detail: "featureFlagPolicies is durable Policy And Prompts state governed by the canonical policy-and-prompts lifecycle."
  },
  {
    id: "invitations",
    owner: "workspace",
    exportMode: "redacted-json",
    deleteMode: "redact",
    detail: "invitations is durable Access And Tenancy state governed by the canonical access-and-tenancy lifecycle."
  },
  {
    id: "notificationPreferences",
    owner: "workspace",
    exportMode: "json",
    deleteMode: "delete",
    detail: "notificationPreferences is durable Notifications state governed by the canonical notifications lifecycle."
  },
  {
    id: "notificationRecords",
    owner: "workspace",
    exportMode: "redacted-json",
    deleteMode: "retain-audit",
    detail: "notificationRecords is durable Notifications state governed by the canonical notifications lifecycle."
  },
  {
    id: "pageRevisions",
    owner: "workspace",
    exportMode: "markdown",
    deleteMode: "delete",
    detail: "Immutable Brain page mutation snapshots used for revision fencing, history, and restore."
  },
  {
    id: "policies",
    owner: "workspace",
    exportMode: "json",
    deleteMode: "delete",
    detail: "policies is durable Policy And Prompts state governed by the canonical policy-and-prompts lifecycle."
  },
  {
    id: "providerConnections",
    owner: "workspace",
    exportMode: "redacted-json",
    deleteMode: "delete",
    detail: "Workspace provider authorization and redacted connection status"
  },
  {
    id: "records",
    owner: "workspace",
    exportMode: "json",
    deleteMode: "delete",
    detail: "Records are workspace-owned application data exported as JSON and removed with the owning workspace."
  },
  {
    id: "transformBlocks",
    owner: "workspace",
    exportMode: "json",
    deleteMode: "retain-audit",
    detail: "transformBlocks is durable Transforms state governed by the canonical transforms lifecycle."
  },
  {
    id: "transformDefinitions",
    owner: "workspace",
    exportMode: "json",
    deleteMode: "delete",
    detail: "transformDefinitions is durable Transforms state governed by the canonical transforms lifecycle."
  },
  {
    id: "transformRuns",
    owner: "workspace",
    exportMode: "json",
    deleteMode: "retain-audit",
    detail: "transformRuns is durable Transforms state governed by the canonical transforms lifecycle."
  },
  {
    id: "usageEvents",
    owner: "workspace",
    exportMode: "json",
    deleteMode: "retain-audit",
    detail: "usageEvents is durable Billing And Entitlements state governed by the canonical billing-and-entitlements lifecycle."
  },
  {
    id: "versionedEntries",
    owner: "workspace",
    exportMode: "json",
    deleteMode: "retain-audit",
    detail: "versionedEntries is durable Generic Versioning state governed by the canonical generic-versioning lifecycle."
  },
  {
    id: "versionFreshness",
    owner: "workspace",
    exportMode: "json",
    deleteMode: "delete",
    detail: "versionFreshness is durable Generic Versioning state governed by the canonical generic-versioning lifecycle."
  },
  {
    id: "webhookEvents",
    owner: "workspace",
    exportMode: "redacted-json",
    deleteMode: "retain-audit",
    detail: "webhookEvents is durable Billing And Entitlements state governed by the canonical billing-and-entitlements lifecycle."
  },
  {
    id: "workflowArtifacts",
    owner: "workspace",
    exportMode: "redacted-json",
    deleteMode: "delete",
    detail: "Large workflow inputs and outputs remain workspace-bound, hash-verified, and retained only while run references or the reviewed audit window require them."
  },
  {
    id: "workflowEffectReservations",
    owner: "workspace",
    exportMode: "redacted-json",
    deleteMode: "retain-audit",
    detail: "External-effect reservations retain redacted idempotency and reconciliation evidence without storing provider payloads."
  },
  {
    id: "workflowEventInstances",
    owner: "workspace",
    exportMode: "redacted-json",
    deleteMode: "retain-audit",
    detail: "Workflow event instances preserve workspace-scoped delivery, principal, ownership, and cleanup state through the audit window."
  },
  {
    id: "workflowRunContextManifests",
    owner: "workspace",
    exportMode: "redacted-json",
    deleteMode: "retain-audit",
    detail: "Immutable run-context manifests bind source, policy, prompt, and model receipts to one workspace-owned workflow run."
  },
  {
    id: "workflowRunEvents",
    owner: "workspace",
    exportMode: "redacted-json",
    deleteMode: "retain-audit",
    detail: "Ordered workflow events are append-only execution evidence exported only through a redacting workspace boundary."
  },
  {
    id: "workflowRunEvidenceSnapshots",
    owner: "workspace",
    exportMode: "redacted-json",
    deleteMode: "retain-audit",
    detail: "Hash-bound evidence snapshots preserve the exact grounded inputs used by a workspace workflow run."
  },
  {
    id: "workflowRunLinks",
    owner: "workspace",
    exportMode: "redacted-json",
    deleteMode: "retain-audit",
    detail: "Parent-child run links retain idempotency, status, and redacted result evidence for workspace-owned subworkflows."
  },
  {
    id: "workflowRuns",
    owner: "workspace",
    exportMode: "redacted-json",
    deleteMode: "retain-audit",
    detail: "Workflow runs are the workspace-owned lifecycle anchor for graph, principal, policy, timing, cleanup, and terminal-state evidence."
  },
  {
    id: "workflowStageRuns",
    owner: "workspace",
    exportMode: "redacted-json",
    deleteMode: "retain-audit",
    detail: "Workflow stage attempts retain bounded status, error, output, and external-effect evidence under their parent run."
  },
  {
    id: "workspaceMembers",
    owner: "workspace",
    exportMode: "redacted-json",
    deleteMode: "redact",
    detail: "workspaceMembers is durable Access And Tenancy state governed by the canonical access-and-tenancy lifecycle."
  },
  {
    id: "workspaces",
    owner: "workspace",
    exportMode: "json",
    deleteMode: "retain-audit",
    detail: "workspaces is durable Access And Tenancy state governed by the canonical access-and-tenancy lifecycle."
  }
] as const;

// prettier-ignore
export const workspaceRetentionRules = [
  {
    resourceId: "accessAuditEvents",
    action: "retain-audit-window",
    detail: "accessAuditEvents is durable Access And Tenancy state governed by the canonical access-and-tenancy lifecycle."
  },
  {
    resourceId: "actionApprovals",
    action: "hash-or-redact-on-export",
    detail: "actionApprovals is durable Action Automation state governed by the canonical action-automation lifecycle."
  },
  {
    resourceId: "actionDigests",
    action: "hash-or-redact-on-export",
    detail: "actionDigests is durable Action Automation state governed by the canonical action-automation lifecycle."
  },
  {
    resourceId: "actionJobs",
    action: "retain-audit-window",
    detail: "actionJobs is durable Action Automation state governed by the canonical action-automation lifecycle."
  },
  {
    resourceId: "actionTriggers",
    action: "retain-until-workspace-delete",
    detail: "actionTriggers is durable Action Automation state governed by the canonical action-automation lifecycle."
  },
  {
    resourceId: "apiKeys",
    action: "hash-or-redact-on-export",
    detail: "apiKeys is durable Access And Tenancy state governed by the canonical access-and-tenancy lifecycle."
  },
  {
    resourceId: "billingPlans",
    action: "retain-until-workspace-delete",
    detail: "billingPlans is durable Billing And Entitlements state governed by the canonical billing-and-entitlements lifecycle."
  },
  {
    resourceId: "brainConnectorRuns",
    action: "retain-until-workspace-delete",
    detail: "Workspace connector run state, optional provider-connection generation fence, bounded counts, failure codes, and successful scope-specific reconciliation receipts."
  },
  {
    resourceId: "brainConnectorRunSeen",
    action: "retain-until-workspace-delete",
    detail: "Append-only source observations used to reconcile one bounded connector run without inferring removals after failure."
  },
  {
    resourceId: "brainEvaluationExamples",
    action: "retain-until-workspace-delete",
    detail: "Explicitly saved Ask Maestro evaluation examples with bounded immutable source references and no copied evidence excerpts."
  },
  {
    resourceId: "brainEvidenceRevisions",
    action: "retain-until-workspace-delete",
    detail: "Immutable provider-neutral evidence revisions with optional hash-bound provider metadata used for exact cited source reopening and integrity verification."
  },
  {
    resourceId: "brainEvidenceSources",
    action: "retain-until-workspace-delete",
    detail: "Current provider-neutral source pointers, hash-bound provider metadata, generations, scope, freshness, and removal state."
  },
  {
    resourceId: "brainPages",
    action: "retain-until-workspace-delete",
    detail: "brainPages is durable Knowledge Brain state governed by the canonical knowledge-brain lifecycle."
  },
  {
    resourceId: "brainRetrievalEntries",
    action: "retain-until-workspace-delete",
    detail: "Bounded current and retired retrieval projections for provider-neutral evidence search."
  },
  {
    resourceId: "brainRetrievalTokens",
    action: "retain-until-workspace-delete",
    detail: "Bounded token postings derived from current evidence and replaced transactionally with retrieval entries."
  },
  {
    resourceId: "citations",
    action: "retain-until-workspace-delete",
    detail: "citations is durable Knowledge Brain state governed by the canonical knowledge-brain lifecycle."
  },
  {
    resourceId: "claims",
    action: "retain-until-workspace-delete",
    detail: "claims is durable Knowledge Brain state governed by the canonical knowledge-brain lifecycle."
  },
  {
    resourceId: "concepts",
    action: "retain-until-workspace-delete",
    detail: "concepts is durable Knowledge Brain state governed by the canonical knowledge-brain lifecycle."
  },
  {
    resourceId: "contextPacks",
    action: "retain-until-workspace-delete",
    detail: "contextPacks is durable Knowledge Brain state governed by the canonical knowledge-brain lifecycle."
  },
  {
    resourceId: "creditLedger",
    action: "retain-audit-window",
    detail: "creditLedger is durable Billing And Entitlements state governed by the canonical billing-and-entitlements lifecycle."
  },
  {
    resourceId: "documentAnnotations",
    action: "retain-until-workspace-delete",
    detail: "documentAnnotations is durable Document Collaboration state governed by the canonical document-collaboration lifecycle."
  },
  {
    resourceId: "documents",
    action: "retain-until-workspace-delete",
    detail: "documents is durable Document Collaboration state governed by the canonical document-collaboration lifecycle."
  },
  {
    resourceId: "documentVersions",
    action: "retain-audit-window",
    detail: "documentVersions is durable Document Collaboration state governed by the canonical document-collaboration lifecycle."
  },
  {
    resourceId: "dsarRequests",
    action: "retain-audit-window",
    detail: "dsarRequests is durable Data Lifecycle state governed by the canonical data-lifecycle lifecycle."
  },
  {
    resourceId: "emailCampaigns",
    action: "retain-until-workspace-delete",
    detail: "Consent-based broadcast campaign content and aggregate delivery state."
  },
  {
    resourceId: "emailDeliveries",
    action: "hash-or-redact-on-export",
    detail: "Idempotent transactional and broadcast recipient delivery state."
  },
  {
    resourceId: "emailSubscribers",
    action: "hash-or-redact-on-export",
    detail: "Workspace-scoped explicit marketing consent and unsubscribe state."
  },
  {
    resourceId: "entitlements",
    action: "retain-audit-window",
    detail: "entitlements is durable Billing And Entitlements state governed by the canonical billing-and-entitlements lifecycle."
  },
  {
    resourceId: "featureFlagPolicies",
    action: "retain-until-workspace-delete",
    detail: "featureFlagPolicies is durable Policy And Prompts state governed by the canonical policy-and-prompts lifecycle."
  },
  {
    resourceId: "invitations",
    action: "hash-or-redact-on-export",
    detail: "invitations is durable Access And Tenancy state governed by the canonical access-and-tenancy lifecycle."
  },
  {
    resourceId: "notificationPreferences",
    action: "retain-until-workspace-delete",
    detail: "notificationPreferences is durable Notifications state governed by the canonical notifications lifecycle."
  },
  {
    resourceId: "notificationRecords",
    action: "hash-or-redact-on-export",
    detail: "notificationRecords is durable Notifications state governed by the canonical notifications lifecycle."
  },
  {
    resourceId: "pageRevisions",
    action: "retain-until-workspace-delete",
    detail: "Immutable Brain page mutation snapshots used for revision fencing, history, and restore."
  },
  {
    resourceId: "policies",
    action: "retain-until-workspace-delete",
    detail: "policies is durable Policy And Prompts state governed by the canonical policy-and-prompts lifecycle."
  },
  {
    resourceId: "providerConnections",
    action: "retain-until-workspace-delete",
    detail: "Workspace provider authorization and redacted connection status"
  },
  {
    resourceId: "records",
    action: "retain-until-workspace-delete",
    detail: "Records are workspace-owned application data exported as JSON and removed with the owning workspace."
  },
  {
    resourceId: "transformBlocks",
    action: "retain-audit-window",
    detail: "transformBlocks is durable Transforms state governed by the canonical transforms lifecycle."
  },
  {
    resourceId: "transformDefinitions",
    action: "retain-until-workspace-delete",
    detail: "transformDefinitions is durable Transforms state governed by the canonical transforms lifecycle."
  },
  {
    resourceId: "transformRuns",
    action: "retain-audit-window",
    detail: "transformRuns is durable Transforms state governed by the canonical transforms lifecycle."
  },
  {
    resourceId: "usageEvents",
    action: "retain-audit-window",
    detail: "usageEvents is durable Billing And Entitlements state governed by the canonical billing-and-entitlements lifecycle."
  },
  {
    resourceId: "versionedEntries",
    action: "retain-audit-window",
    detail: "versionedEntries is durable Generic Versioning state governed by the canonical generic-versioning lifecycle."
  },
  {
    resourceId: "versionFreshness",
    action: "retain-until-workspace-delete",
    detail: "versionFreshness is durable Generic Versioning state governed by the canonical generic-versioning lifecycle."
  },
  {
    resourceId: "webhookEvents",
    action: "hash-or-redact-on-export",
    detail: "webhookEvents is durable Billing And Entitlements state governed by the canonical billing-and-entitlements lifecycle."
  },
  {
    resourceId: "workflowArtifacts",
    action: "retain-audit-window",
    detail: "Large workflow inputs and outputs remain workspace-bound, hash-verified, and retained only while run references or the reviewed audit window require them."
  },
  {
    resourceId: "workflowEffectReservations",
    action: "retain-audit-window",
    detail: "External-effect reservations retain redacted idempotency and reconciliation evidence without storing provider payloads."
  },
  {
    resourceId: "workflowEventInstances",
    action: "retain-audit-window",
    detail: "Workflow event instances preserve workspace-scoped delivery, principal, ownership, and cleanup state through the audit window."
  },
  {
    resourceId: "workflowRunContextManifests",
    action: "retain-audit-window",
    detail: "Immutable run-context manifests bind source, policy, prompt, and model receipts to one workspace-owned workflow run."
  },
  {
    resourceId: "workflowRunEvents",
    action: "retain-audit-window",
    detail: "Ordered workflow events are append-only execution evidence exported only through a redacting workspace boundary."
  },
  {
    resourceId: "workflowRunEvidenceSnapshots",
    action: "retain-audit-window",
    detail: "Hash-bound evidence snapshots preserve the exact grounded inputs used by a workspace workflow run."
  },
  {
    resourceId: "workflowRunLinks",
    action: "retain-audit-window",
    detail: "Parent-child run links retain idempotency, status, and redacted result evidence for workspace-owned subworkflows."
  },
  {
    resourceId: "workflowRuns",
    action: "retain-audit-window",
    detail: "Workflow runs are the workspace-owned lifecycle anchor for graph, principal, policy, timing, cleanup, and terminal-state evidence."
  },
  {
    resourceId: "workflowStageRuns",
    action: "retain-audit-window",
    detail: "Workflow stage attempts retain bounded status, error, output, and external-effect evidence under their parent run."
  },
  {
    resourceId: "workspaceMembers",
    action: "retain-audit-window",
    detail: "workspaceMembers is durable Access And Tenancy state governed by the canonical access-and-tenancy lifecycle."
  },
  {
    resourceId: "workspaces",
    action: "retain-audit-window",
    detail: "workspaces is durable Access And Tenancy state governed by the canonical access-and-tenancy lifecycle."
  }
] as const;
